#!/usr/bin/env bash
# Regenerate SKILLS.md: one row per skill with its source, pinned commit, and license.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
out=SKILLS.md
{
  echo "# Skill index"
  echo
  echo "Generated by \`scripts/build-index.sh\` (runs on every sync). Do not edit by hand."
  echo
  section=""
  maintained=()
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == "## ---- "* ]]; then
      section=$(sed -E 's/^## ---- (.*) ----$/\1/' <<<"$line")
      echo; echo "## $section"; echo
      echo "| Skill | Source (pinned) | License | Description |"
      echo "|---|---|---|---|"
      continue
    fi
    [[ -z "$line" || "$line" == \#* ]] && continue
    IFS=$'\t' read -r repo ref path name flags <<< "$line"
    f="skills/$name/SKILL.md"; [[ -f "$f" ]] || continue
    desc=$(awk 'NR==1{next} /^---/{exit} {print}' "$f" \
      | awk '/^description:/{d=1; sub(/^description:[ ]*/,""); print; next} d&&/^[ \t]/{print; next} d{exit}' \
      | tr '\n' ' ' | sed -E 's/^[>|-]+ *//; s/^["'\'']//; s/["'\'' ]+$//; s/\|/\\|/g; s/  +/ /g' | cut -c1-160)
    lic=$(sed -n 's/^License: //p' "skills/$name/UPSTREAM.md" 2>/dev/null | sed -E 's/^none found.*/none (local only)/')
    [[ -f "skills/$name/LICENSE.upstream" ]] && lic=$(grep -m1 -o -E 'MIT|Apache License|BSD|MPL' "skills/$name/LICENSE.upstream" | sed 's/Apache License/Apache-2.0/' || echo "$lic")
    note=""; [[ " $flags " == *" local "* ]] && note=" *(local only, not committed)*"
    [[ " $flags " == *" patch-review-r "* ]] && note="$note *(patched: bundles upstream rules)*"
    base=$(basename "$path"); [[ "$path" != "." && "$base" != "$name" ]] && note="$note *(upstream: $base)*"
    url="https://github.com/$repo/tree/$ref"; [[ "$path" != "." ]] && url="$url/$path"
    [[ "$repo" == jeremy-allen/* ]] && lic="none (used with author's OK)"
    printf '| `%s`%s | [%s](%s) @ `%s` | %s | %s |\n' \
      "$name" "$note" "$repo" "$url" "${ref:0:7}" "$lic" "$desc"
  done < sources.tsv
  echo; echo "## Maintained in this repo"; echo
  echo "| Skill | Description |"; echo "|---|---|"
  for d in skills/*/; do
    n=$(basename "$d"); [[ -f "$d/UPSTREAM.md" ]] && continue
    desc=$(grep -m1 '^description:' "$d/SKILL.md" | sed -E 's/^description:[ ]*//; s/\|/\\|/g' | cut -c1-160)
    echo "| \`$n\` | $desc |"
  done
} > "$out"
echo "wrote $out"
